### ISSUE TITLE
Is it possible to specify column types when creating a table from Excel?

### ISSUE THREAD

**Issue by brentajones** [wireservice/agate-excel#6]
It seems like `Table.from_xls()` only takes a file (and sheet) as an argument. The default TypeTester is incorrectly parsing number codes (similar to FIPS codes) as numbers instead of strings.

Is there a better way of forcing column types when importing from Excel? I could compute new columns, but it seems like something that could be done on creation.

**Comment by onyxfish** [comment]
Hmmm, after thinking about this for a little bit, I think you're right, we need a way to specify the TypeTester. That's potentially going to be pretty confusing, since really the XLS should "know" what the types of its columns are, but I think the case you describe makes it unavoidable.

Would happily accept a pull request adding that, or can work it up next time I hack on this.
