### ISSUE TITLE
Extract a series of sheets into tables

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate-excel#8]

**Comment by jpmckinney** [comment]
Related https://github.com/wireservice/csvkit/pull/473

**Comment by jpmckinney** [comment]
What would the API be for this? For csvkit integration, it'd be best if `from_xls(all_sheets=True)` returned a list in which the first item is the `sheet` table, and the second item is a list of all sheets as tables. This is so that both `--sheet` and `--write-all-sheets` can be set, with only the sheet specified by `--sheet` being piped to the next command.

**Comment by jpmckinney** [comment]
Actually, we should maybe make this `agate.TableSet.from_xls`.

**Comment by jpmckinney** [comment]
Hmm, can't do that because TableSet would expect all Excel sheets to have the same structure (i.e. TableSet raises `'Not all tables have the same column types!'` and/or `'Not all tables have the same column names!'`).

@onyxfish Where should we hang this method on? I have it implemented - I just don't know what class to put it on.

**Comment by jpmckinney** [comment]
I think #19 closes this, unless the intention was to add TableSet methods in the case where multiple sheets are expected to have the same structure.
